# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bn42_Gb5qIuXs6qHi5fQB60IOvd4u8bd
"""

myself = "Héctor Hernández"
city = "Mexico City"
phone = "+52 5562194933"
mail = "hector.hdez.08@gmail.com"
summary = """Analytical professional with knowledge generating and analyzing
data reports for management. Strategic mindset that focuses on problem solving
tasks and maintaining priorities on strict deadlines."""

experience = [{
    "place": "frelance",
    "job": "Email Server Administrator",
    "start": "2022-09-01",
    "end": None,
	"where": "Online",
    "expertise": ["hosting", "server administration", "linux", "ssh"]

},
{  "place": "frelance",
    "job": "Web page developer",
    "start": "2022-09-01",
    "end": None,
	"where": "Online",
    "expertise": ["hosting", "server administration", "html", "css", "hugo", "ngix", "ssh"]
},
{  "place": "frelance",
    "job": "Foreign Language Teacher",
    "start": "2021-06-01",
    "end": None,
	"where": "Online",
    "expertise": ["teaching spanish to beginners", "teaching portuguese to beginners"]
},
{  "place": "at&t",
    "job": "Customer Service",
    "start": "2017-08-01",
    "end": "2017-08-01",
	"where": "mexico city",
    "expertise": ["customer service", "problem-solving", "stress management in difficult situations", "use of tools for processing and collection data"]
}]

education = [{
    "university": "universidad autónoma metropolitana",
    "city": "mexico city",
    "degree": "bachelors",
    "course": "economics",
    "start": "2015-05-01",
    "end": "2023-09-01"
}]

skills_info = list()
skills = [
    "excel", "linux", "bash", "data analysis",
    "r", "python", "pandas", "vps servers",
    "ssh", "nginx", "sqlite3", "microsoft office",
    "inferential statistics", "data modeling", "math",
    "statistics", "data science", "java script",
    "retrieve data", "processing data", "html",
    "web scraping", "analytical thinking", "problem-solving",
    "critical thinking", "time management", "public speaking",
    "attention to detail", "good listening", "to lead others",
    "to be able to explain certain topics clearly"
    ]

for i in skills:
    skills_info.append("- " + i.capitalize() + "\n")

skills_info = "".join(skills_info)

def DateMY(date):
  month = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
  DateCourse = date.split("-")
  month = month[int(DateCourse[1]) - 1]
  return "{} {}".format(month, DateCourse[0])
  #return(DateCourse)

for i in education:
  name = i["university"].capitalize()
  name = " ".join([ j.capitalize() for j in name.split() ])
  city = i["city"].capitalize()
  start = DateMY(i["start"])
  end = DateMY(i["end"])
  degree = i["degree"]
  course = i["course"].capitalize()

  if degree == "bachelors":
    education_info = "{}, {} - {}\nBachelor's degree in {}".format(name, start, end, course)

coursera = [{
	"provider": "coursera",
	"name": "fundamentos de la escritura",
	"date": "2021-05-01",
	"id": "b29yfww7kayg",
	"specialization": None,
	"order": None,
	"university": "tecnológico de monterrey",
	"link": "https://coursera.org/share/971f82b2199de960a0697b9fcdc98673",
	"expertise": ["normas ortográficas",
	  "redactar de forma correcta",
	  "planificar textos",
	  "utilizar estrategias de cohesión y adecuación"
	]
},
{
	"provider": "coursera",
	"name": "pluralidades em português brasileiro",
    "date": "2021-09-01",
    "id": "z9r8pwpxkqrs",
	"specialization": None,
	"order": None,
	"university": "universidade estadual de campinas",
	"link": "https://coursera.org/share/315ed4e9a432a2bacf43f0c4dbddcc86",
	"expertise": ["advanced portuguese"]
},
{
	"provider": "coursera",
	"name": "programming for everybody (getting started with python)",
    "date": "2021-11-01",
    "id": "27572z8deqpn",
	"specialization": "python for everybody",
	"order": 1,
	"university": "university of michigan",
	"link": "https://coursera.org/share/ba83c1f356df32d7b476dbee0be60b1f",
	"expertise": [
	"python syntax and semantics",
    "basic programming language",
    "computer programming",
    "python programming"
	]
},
{
	"provider": "coursera",
	"name": "python data structures",
    "date": "2022-02-01",
    "id": "carsq5ewfttd",
	"specialization": "python for everybody",
	"order": 2,
	"university": "university of michigan",
	"link": "https://coursera.org/share/44c1f463807860cdd62e0b4145f3b196",
	"expertise": [
	"python syntax and semantics",
    "data structure",
    "tuple",
    "python programming"
	]
},
{
	"provider": "coursera",
	"name": "enhance your writing with adverb clauses",
    "date": "2022-10-01",
    "id": "u3kkrxbbnhxk",
	"specialization": 'Learn English: Writing Effectively with Complex Sentences Learn English: Writing Effectively with Complex Sentences',
	"order": 1,
	"university": "university of california, irvine",
	"link": "https://coursera.org/share/069fe34d2bf1c6e6f2b00b14b9a39355",
	"expertise": ["english"]
},
{
	"provider": "coursera",
	"name": "linux and bash for data engineering",
    "date": "2022-09-01",
    "id": "p8yph5be4nh3",
	"specialization": "python, bash and sql essentials for data engineering",
	"order": 2,
	"university": "duke university",
	"link": "https://coursera.org/share/b904c72cc60884ae56e89c5a6dca70d7",
	"expertise": ["bash", "database (bdms)", "data management", "linux"]
},
{
	"provider": "coursera",
	"name": "crea tu artículo científico con latex",
    "date": "2022-09-01",
    "id": "2cxfjxjebp89",
	"specialization": None,
	"order": None,
	"university": "coursera project network",
	"link": "https://coursera.org/share/78c1d42272dad8eda34ad3ed809eeaa6",
	"expertise": ["latex", "articulos científicos", "edición de formato"]
},
{
	"provider": "coursera",
	"name": "introduction to probability and data with r",
    "date": "2022-09-01",
    "id": "zghhj2rksne5",
	"specialization": "data analysis with r",
	"order": 1,
	"university": "duke university",
	"link": "https://coursera.org/share/e2493eceb9c9aba9466b0122147febd7",
	"expertise": [
	"Probability & Statistics",
	"Probability Distribution",
	"General Statistics",
	"Data Analysis",
	"Experiment",
	"Bayesian Statistics"
	]


},
{
	"provider": "coursera",
	"name": "introduction to bash shell scripting",
    "date": "2022-09-01",
    "id": "zh5l8hsbpq69",
	"specialization": None,
	"order": None,
	"university": "coursera project network",
	"link": "https://coursera.org/share/2c9e0c03c9c0b4b3a2703240c57648b1",
	"expertise": [
	"scripting",
     "linux",
     "bash",
     "creating aliases",
     "creating cron jobs",
     "manipulating files and directories",
     "writing bash shell script"
	]
},
{
	"provider": "coursera",
	"name": "using python to access web data",
    "date": "2022-09-01",
    "id": "ssu7n3vfxft7",
	"specialization": "python for everybody",
	"order": 3,
	"university": "university of michigan",
	"link": "https://coursera.org/share/a815543e620d225335c24ae1c635b777",
	"expertise": ["regex", "json", "xml", "python programming", "web scraping"]
},
{
  "provider": "coursera",
  "name": "introducción a data science: programación estadística con r",
  "date": "2022-09-01",
  "id": "lnx6lbqrcemw",
  "university": "universidad nacional autónoma de méxico",
  "specialization": None,
  "order": None,
  "link": "https://coursera.org/share/44553866e3c7052fbed125b2093caab2",
  "expertise": ["graphics", "r", "rstudio", "exploratory data analysis"]
},
{
	"provider": "coursera",
	"name": "introduction to html5",
    "date": "2023-03-01",
    "id": "5ajxh35rjutd",
	"university": "university of michigan",
	"specialization": "web design for everybody: basics of web development & coding",
	"order": 1,
	"link": "https://coursera.org/share/a07cb03b95bb78b672178de8219dcfb5",
	"expertise": ["web desing", "html", "web page"]
},
{
	"provider": "coursera",
	"name": "using databases with python",
	"date": "2022-11-01",
	"id": "42wl5akcgvj9",
	"specialization": "Python for Everybody",
	"order": 4,
	"university": "university of michigan",
	"link": "https://coursera.org/share/e9e742213f079bca6290547ab53fe798",
	"expertise": ["python programming", "database (bdms)", "sqlite", "sql"]
},
{
	"provider": "coursera",
	"name": "inferential statistics",
    "date": "2023-04-01",
    "id": "vdd297w4gvds",
	"specialization": "data analysis with r",
	"order": 2,
	"university": "duke university",
	"link": "https://coursera.org/share/717c098745987c1dd4ea879206dbb904",
	"expertise": [
	"Probability & Statistics",
	"General Statistics",
	"Data Analysis",
	"Statistical Programming"
	]
},
{
	"provider": "coursera",
	"name": "web application technologies and django",
	"date": "2023-03-01",
	"id": "2zlzsrtnycaf",
	"specialization": "django for everybody",
	"order": 1,
	"university": "university of michigan",
	"link": "https://coursera.org/share/45fce04af68c4146b757eb2c0dac77b1",
	"expertise": ["css", "html", "http", "sql","django"]
},
{
	"provider": "coursera",
	"name": "python and pandas for data engineering",
    "date": "2022-10-01",
    "id": "a5pzuxydcsmf",
	"specialization": "python, bash and sql essentials for data engineering",
	"order": 1,
	"university": "duke university",
	"link": "https://coursera.org/share/2bd9480c456422404239d08a06a49d89",
	"expertise": ["vim", "python programming", "pandas", "data structure"]
},
{
	"provider": "coursera",
	"name": "create charts and dashboard using google sheets",
    "date": "2023-06-01",
    "id": "at2xkna9bced",
	"specialization": None,
	"order": None,
	"university": "coursera project network",
	"link": "https://www.coursera.org/account/accomplishments/certificate/AT2XKNA9BCED",
	"expertise": [
	"Spreadsheet",
	"Google Sheets",
	"Charts and Graphs",
	"Data Analysis",
	"Data Visualization (DataViz)"
	]
},
{
	"provider": "coursera",
	"name": "database design and basic sql in postgresql",
	"date": "2023-06-01",
	"id": "xsczp6gcc5hd",
	"specialization": "PostgreSQL for Everybody Specialization",
	"order": 1,
	"university": "university of michigan",
	"link": "https://www.coursera.org/account/accomplishments/certificate/xsczp6gcc5hd",
	"expertise": [
	"psql",
	"sql",
	"one-to-many",
	"many-to-many"
	]
},
{
	"provider": "coursera",
	"name": "capstone: retrieving, processing, and visualizing data with python",
    "date": "2023-02-01",
    "id": "zs5d538sasv9",
	"specialization": "Python for Everybody",
	"order": 5,
	"university": "university of michigan",
	"link": "https://coursera.org/share/5d4c37cb948afb167fe9fd17921f0ff3",
	"expertise": ["data analysis", "python programming", "database (bdms)", "data visualization (dataviz)"]
},
{
	"provider": "coursera",
	"name": "scripting with python and sql for data engineering",
    "date": "2023-03-01",
    "id": "ybvx7wtuzw2z",
	"specialization": "python, bash and sql essentials for data engineering",
	"order": 3,
	"university": "duke university",
	"link": "https://coursera.org/share/0a7c8eef12772f3dacb1ea2469e17d91",
	"expertise": ["database (bdms)", "python programming", "web scraping", "mysql", "sql"]
},
{
	"provider": "coursera",
	"name": "introduction to data science in python",
    "date": "2023-03-01",
    "id": "wfeepy38tle5",
	"specialization": "applied data science with python",
	"order": 1,
	"university": "university of michigan",
	"link": "https://coursera.org/share/fea1d9e03695e6a9e90effceafdc7521",
	"expertise": ["python programming", "numpy", "pandas", "data cleaning"]
}]

course_info = list()

for i in coursera:
  name = "**" + i["name"].capitalize() + "**"
  university = "_" + i["university"].capitalize() + "_"
  date = DateMY(i["date"])
  skills = "Relevant skills: " + ", ".join(e.capitalize() for e in i["expertise"])

  course_info.append("{}\n{}, {}\n{}\n\n".format(name, university, date, skills))

certification_info = "\n".join(course_info)

experience_info = list()

for i in experience:
    place = i["place"].capitalize()
    job = " ".join([j.capitalize() for j in i["job"].split()])
    start = DateMY(i["start"])
    if i["end"] == None:
      end = "Current"
    else:
      end = DateMY(i["end"])
    where = i["where"].capitalize()
    skills =  "".join(["- "+j.capitalize() +"\n" for j in i["expertise"]])
    experience_info.append("{}\n{}\n{}\n{} - {}\n{}".format(job, place, where, start, end, skills))

experience_info = "\n".join(experience_info)

header = "# {}\n{} | {} | {}".format(myself, city, phone, mail)
summary_info = "\n\n## Summary\n\n***\n\n{}".format(summary)
education_info = "\n\n## Education\n\n***\n\n{}".format(education_info)
experience_info = "\n\n## Experience\n\n***\n\n{}".format(experience_info)
certification_info = "\n\n## Certifications\n\n***\n\n{}".format(certification_info)
skills_info = "\n\n## Skills\n\n***\n\n{}".format(skills_info)


with open("test.md", "w") as file:
   file.write("{}{}{}{}{}{}".format(header, summary_info, education_info, experience_info, certification_info, skills_info))